  name: Deploy to EC2

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      name: Push to EC2
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1
          with:
            host: 13.49.246.72
            username: ubuntu
            key: ${{ secrets.PRIVATE_SSH_KEY }}
            port: 22
            script: |
              cd ci-cd
              git pull origin main
              ~/npm install
              npm run build
          
              pm2 restart ci-cd
              
            
