name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 51.21.195.168
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Change to project directory
            cd ~/ci-cd
            
            # Pull the latest changes
            git init  
            git pull origin main
            
            # Install dependencies
            npm install
            npm run build  
            
            # Restart PM2 processes (adjust the app name if necessary)
             pm2 restart 0
            
          
